// export { default as Desc } from "./Desc";
// export { default as Card } from "./Card/Card";
export { default as Tabs } from "./Tabs/Tabs.tsx";
// export { default as Title } from "./Title/Title";
export { default as Button } from "./Button/index.tsx";
// export { default as Loader } from "./Loader/Loader";
// export { default as About } from "./About/About.jsx";
// export { default as PhotoCard } from "./Card/PhotoCard";
// export { default as DatailCard } from "./TopCard/index";
export { default as EmptyState } from "./EmptyState/index.tsx";
